import { createAudioPlayer, setAudioModeAsync } from 'expo-audio';
import type { AudioPlayer } from 'expo-audio';

import type { SoundKey } from '@/game/phaser/bridge/protocol';

import { errorReporter } from './errorReporting';
import boosterSound from '../../assets/audio/booster.wav';
import cascadeSound from '../../assets/audio/cascade.wav';
import invalidSound from '../../assets/audio/invalid.wav';
import loseSound from '../../assets/audio/lose.wav';
import matchSound from '../../assets/audio/match.wav';
import musicLoop from '../../assets/audio/music-loop.wav';
import objectiveSound from '../../assets/audio/objective.wav';
import specialSound from '../../assets/audio/special.wav';
import swapSound from '../../assets/audio/swap.wav';
import tapSound from '../../assets/audio/tap.wav';
import winSound from '../../assets/audio/win.wav';

/**
 * Sound architecture: short SFX players are created lazily and reused; one looping music
 * player runs while music is enabled and the app is in the foreground. All audio is optional
 * and failures are swallowed (reported in dev) so sound can never break gameplay.
 * Assets are original placeholders generated by scripts/generate-audio.mjs.
 */
const SFX_SOURCES: Record<SoundKey, number> = {
  tap: tapSound,
  swap: swapSound,
  invalid: invalidSound,
  match: matchSound,
  cascade: cascadeSound,
  special: specialSound,
  booster: boosterSound,
  objective: objectiveSound,
  win: winSound,
  lose: loseSound,
};

const SFX_VOLUME = 0.6;
const MUSIC_VOLUME = 0.25;

class AudioService {
  private sfxEnabled = true;
  private musicEnabled = true;
  private foreground = true;
  private configured = false;
  private readonly players = new Map<SoundKey, AudioPlayer>();
  private music: AudioPlayer | null = null;

  private ensureMode(): void {
    if (this.configured) return;
    this.configured = true;
    // Respect the iOS silent switch and mix politely with other apps' audio.
    setAudioModeAsync({ playsInSilentMode: false, interruptionMode: 'mixWithOthers' }).catch(
      (error: unknown) => errorReporter.captureException(error, { area: 'audio' }),
    );
  }

  configure(options: { sfxEnabled: boolean; musicEnabled: boolean }): void {
    this.sfxEnabled = options.sfxEnabled;
    this.musicEnabled = options.musicEnabled;
    this.syncMusic();
  }

  setForeground(foreground: boolean): void {
    this.foreground = foreground;
    this.syncMusic();
  }

  play(key: SoundKey): void {
    if (!this.sfxEnabled) return;
    try {
      this.ensureMode();
      let player = this.players.get(key);
      if (!player) {
        player = createAudioPlayer(SFX_SOURCES[key]);
        player.volume = SFX_VOLUME;
        this.players.set(key, player);
      }
      const active = player;
      active
        .seekTo(0)
        .then(() => active.play())
        .catch(() => undefined);
    } catch (error) {
      errorReporter.captureException(error, { area: 'audio', extra: { key } });
    }
  }

  private syncMusic(): void {
    const shouldPlay = this.musicEnabled && this.foreground;
    try {
      if (shouldPlay) {
        this.ensureMode();
        if (!this.music) {
          this.music = createAudioPlayer(musicLoop);
          this.music.loop = true;
          this.music.volume = MUSIC_VOLUME;
        }
        if (!this.music.playing) this.music.play();
      } else if (this.music?.playing) {
        this.music.pause();
      }
    } catch (error) {
      errorReporter.captureException(error, { area: 'audio', extra: { music: shouldPlay } });
    }
  }
}

export const audio = new AudioService();
