/**
 * Bundles the Phaser game (src/game/phaser/runtime/main.ts + shared core rules) into ONE
 * self-contained HTML document and writes it as a TypeScript string module that React Native
 * loads into the WebView. No CDN or network access is needed at runtime.
 *
 * Output (git-ignored, regenerated on `npm install` and `npm run build:game`):
 *   src/game/phaser/generated/gameHtml.ts
 */
import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'src', 'game', 'phaser', 'generated');

const result = await build({
  entryPoints: [path.join(root, 'src', 'game', 'phaser', 'runtime', 'main.ts')],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  // Expo SDK 57 targets iOS 15.1+ and Android WebView (evergreen Chromium).
  target: ['es2020'],
  minify: true,
  write: false,
  legalComments: 'none',
  tsconfig: path.join(root, 'tsconfig.json'),
  define: {
    'process.env.NODE_ENV': '"production"',
    // Phaser build flags: WebGL + Canvas renderers, no plugin camera/FB features.
    CANVAS_RENDERER: 'true',
    WEBGL_RENDERER: 'true',
    WEBGL_DEBUG: 'false',
    EXPERIMENTAL: 'false',
    PLUGIN_3D: 'false',
    PLUGIN_CAMERA3D: 'false',
    PLUGIN_FBINSTANT: 'false',
    FEATURE_SOUND: 'false',
  },
  logLevel: 'warning',
});

// Prevent the inline script from terminating its own <script> element.
const js = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover" />
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob:; connect-src 'none'; media-src 'none'; frame-src 'none'; base-uri 'none'; form-action 'none'" />
<title>Campus Rally Board</title>
<style>
  html, body { margin: 0; padding: 0; width: 100%; height: 100%; overflow: hidden; background: transparent;
    -webkit-user-select: none; user-select: none; -webkit-touch-callout: none; touch-action: none;
    -webkit-tap-highlight-color: transparent; }
  #game { width: 100%; height: 100%; }
  canvas { display: block; }
</style>
</head>
<body>
<div id="game" role="img" aria-label="Campus Rally game board"></div>
<script>${js}</script>
</body>
</html>`;

const hash = createHash('sha256').update(html).digest('hex').slice(0, 12);
mkdirSync(outDir, { recursive: true });
writeFileSync(
  path.join(outDir, 'gameHtml.ts'),
  `// AUTO-GENERATED by scripts/build-game.mjs — do not edit. Rebuild with \`npm run build:game\`.\n` +
    `/* eslint-disable */\n` +
    `export const GAME_HTML_HASH = ${JSON.stringify(hash)};\n` +
    `export const GAME_HTML: string = ${JSON.stringify(html)};\n`,
);
console.log(
  `[build-game] wrote src/game/phaser/generated/gameHtml.ts (${(html.length / 1024).toFixed(0)} KB, ${hash})`,
);
